"use client";
import { usePathname } from "next/navigation";
import React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import LenisScroll from "../LenisScroll";
import NavBarTwo from "./NavBarTwo";
import Footer from "./Footer";
import Navbar from "./Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Providers = ({ children }: { children: React.ReactNode }) => {
  const pathname = usePathname();
  const isHomePage = pathname === "/";
  return (
    <>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} relative overflow-x-hidden antialiased`}
        >
          <LenisScroll />
          {isHomePage ? <NavBarTwo className="absolute" /> : <Navbar />}
          {children}
          <Footer />
          <script src="./node_modules/preline/dist/preline.js"></script>
        </body>
      </html>
    </>
  );
};

export default Providers;
